### PR TITLE
Try adding root variant config file

### PR DESCRIPTION
**Pull request by jakirkham**
Makes a tweak to search for the variant config file in the top-level directory of the `root` environment. If it finds it, this file gets highest priority (even over user specified ones). This would allow `conda-forge-pinning` to be pulled in, but would make it optional. That way users outside the org can specify this another way.

### CODE REVIEW

**Comment by msarahan** [comment]
Whoa, I definitely would not put this above user-specified ones.  What's your thinking on that?  Why not just append it?

**Comment by jakirkham** [comment]
Thought about that initially. Figured the user specified ones would serve as further refinement (e.g. ones included in a feedstock).

Besides if a user doesn't want this, they can easily remove `conda_build_config.yaml` from `root` (uninstalling or straight deleting if it was added manually). I suppose we could also add a flag to completely ignore the `root` copy of `conda_build_config.yaml`.

**Comment by msarahan** [comment]
Ah, yes, you're totally right.  You do want it at the beginning of the list, so that later ones will override it.  Unfortunately, anything specified in ``variant_config_files`` as is done here will end up higher in priority than configuration in the feedstock.  The only way to get lower priority is to use conda-build's default paths, or the condarc setting from ``conda_build/config-file`` as documented at https://conda.io/docs/user-guide/tasks/build-packages/variants.html#creating-conda-build-variant-config-files

**Comment by jakirkham** [comment]
Just to make sure I understand correctly, you're saying that the home directory, `.condarc`, and the recipe, will be check first before getting to this list? That makes sense. So a couple of thoughts IIUC.

First we could discuss adding this as the first search path in `conda-build`. Assuming that is agreeable, it seems like a good idea. Though I don't know if there are other concerns that introduces for `conda-build`. Not to mention that still won't fix the full problem as explained below.

Second we probably want to disable `conda-build`'s behavior of search the home directory and `.condarc` in this case. Namely because we don't want users accidentally messing up their feedstocks during re-rendering based on settings they use locally. Also we don't want to suggest users muck with their local settings to get a correct re-rendering.

For a little history, we had the same problem with channels in `.condarc` messing with re-rendering and confusing users. We ended up doing the same thing with channels and channel priority for exactly this reason. Namely it uses `conda-forge.yml` as the source of truth for channels. ( https://github.com/conda-forge/conda-smithy/pull/401 )

**Comment by jakirkham** [comment]
Does that makes sense? Questions? Thoughts? :)

**Comment by msarahan** [comment]
Yes, it makes sense.  I agree that the ability to exclusively choose a file rather than combine them with overrides and hope for the best is probably wise.

I'm fixing some annoying rendering issues right now (multiple outputs + dynamic pinning + templated output names), and after that I have to work on some other unrelated things.  If you feel up for submitting a PR for your proposed operation, go for it.  Otherwise, I'll come back to it next week some time.

**Comment by jakirkham** [comment]
Another thought that I don't think I explicitly spelled out. We might also reuse the solution that we did with channels. Namely have the default be to use `conda-forge-pinning` and whatever is in the recipe if nothing else is specified in `conda-forge.yml`. Thus allowing the user to override this as need in `conda-forge.yml` and then re-render for the updated behavior.

**Comment by jakirkham** [comment]
Closing this out as subsequent changes to `conda-build` via PR ( https://github.com/conda/conda-build/pull/2661 ) and developments at `conda-smithy` for this functionality in PR ( https://github.com/conda-forge/conda-smithy/pull/652 ) have made this irrelevant.

**Comment by msarahan** [comment]
Thanks for the housekeeping. Glad we came up with a good way.

**Pull request closed without merging**
